Lesson8
Oxanailyushchenko/Coding-Girls pull request #5
Opened 2018-07-03 15:44 UTC by Oxanailyushchenko

2018-07-03 23:17 UTC, Afelua requested changes

2018-07-03 23:17 UTC, Afelua commented on fonts_css.css
> +	font-family: AvenirNextCyr-Regular, sans-serif;
Здесь еще надо прописать     font-weight: 400; Т.к. по умолчанию браузер для h1/h2 всегда делает жирный шрифт, а нам он не нужен, надо переопределить.

2018-07-03 23:17 UTC, Afelua commented on fonts_css.css
> +
Комментарий аналогичен выше.

2018-07-03 23:17 UTC, Afelua commented on index.html
> +      <input class="input_email" type="text" placeholder="Your Email" id="email">
Форма с e-mail не должна быть такой длинной:
<img width="836" alt="screen shot 2018-07-04 at 02 12 58" src="https://user-images.githubusercontent.com/8777546/42248718-ca04a9c6-7f2f-11e8-9720-3f415baf80cd.png">

2018-07-03 23:17 UTC, Afelua commented on fonts_css.css
> +	font-family: AvenirNextCyr-Regular, sans-serif;
Также у вас появилась левая полоса справа:

<img width="836" alt="screen shot 2018-07-04 at 02 12 58" src="https://user-images.githubusercontent.com/8777546/42248814-2dff986e-7f30-11e8-895f-7e1b8708b67d.png">

Это за счет того, что элемент .title занимает 100% экрана, а вы его еще и подвинули на 112px. Чтобы этого не было, нужно ему присвоить     display: inline-block;

2018-07-04 09:56 UTC, Oxanailyushchenko commented on index.html
> +      <input class="input_email" type="text" placeholder="Your Email" id="email">
![2018-07-04_12-55-00](https://user-images.githubusercontent.com/39965522/42270497-afb87d40-7f89-11e8-99b6-e9a4b166fdb2.png)
Странно, у меня по макету именно такой длины и есть форма

2018-07-04 09:57 UTC, Oxanailyushchenko commented on fonts_css.css
> +	font-family: AvenirNextCyr-Regular, sans-serif;
Прописала и то и другое

2018-07-05 20:01 UTC, Afelua commented on fonts_css.css
> +	font-family: AvenirNextCyr-Regular, sans-serif;
В файле fonts_css.css вы определили шрифт через font-weight: 400;, а затем нужно при его использовании тоже указать font-weight: 400; в файле styles.css

2018-07-05 20:03 UTC, Afelua approved these changes

2018-07-06 12:35 UTC, Oxanailyushchenko commented on fonts_css.css
> +	font-family: AvenirNextCyr-Regular, sans-serif;
Поправила, теперь все хорошо отображается)

2018-07-06 12:37 UTC, merged